# Generated by Django 6.0.3 on 2026-05-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rola', models.CharField(max_length=50)),
                ('haslo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('opis', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('laboratorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labflow.laboratorium')),
            ],
        ),
        migrations.CreateModel(
            name='Serwis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateTimeField()),
                ('opis', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labflow.sprzet')),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labflow.uzytkownik')),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labflow.sprzet')),
            ],
        ),
    ]
